### ISSUE TITLE
Failed to set up the conda environment due to package conflicts

### ISSUE THREAD

**Issue by mingyang-wang26** [dnandha/mopac#1]
Hi, 
thank you very much for your paper and code! It is super helpful to me.

However, I had some troubles while setting up the environment. Many package conflicts are being reported(part of the error info shown in the image). I guess it results from the specified version of the packages in the environment.yml file. I tried to change several versions according to the error information but still cannot solve the problem. 

Could you check the requirements file and update it if it's possible?
Thanks a lot!

![image](https://user-images.githubusercontent.com/58189318/118142800-023b1b00-b40b-11eb-8152-33b712d4b11f.png)

**Comment by asmorgan24** [comment]
Thanks for finding this. Turns out the conda cffi version was out of date. Updated from 1.11.5 to 1.14.5 in the environment.yml file. Find changes in the [commit.](https://github.com/dnandha/mopac/commit/058128183d16b7f8dcdaf2758a38b10f348566aa)

**Comment by mingyang-wang26** [comment]
@asmorgan24 Thanks for the update and I set up the env successfully!
